# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: huntout.me
description: 'Huntout me? Yes, Huntout is here.'
author:
  name: Huntout Zhang
  email: huntout@gmail.com
baseurl: http://huntout.me
rssurl: http://feeds.feedburner.com/huntout

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess', '.nojekyll']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true
debug: true

permalink: pretty

# Markdown library
markdown: redcarpet
  # extensions: ['fenced_code_blocks', 'smart']

pygments: true

encoding: utf-8

source: app
destination: .jekyll